repos:
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.3.1
      hooks:
          - id: autoflake
            verbose: true

    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports
            verbose: true

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.16.0
      hooks:
          - id: pyupgrade
            verbose: true
            args: [--py312-plus]

    - repo: https://github.com/timothycrosley/isort
      rev: 5.13.2
      hooks:
          - id: isort
            verbose: true

    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black
            verbose: true

    - repo: local
      hooks:
          - id: pylint
            verbose: true
            name: pylint
            entry: pylint -rn -sn
            language: system
            types: [python]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.1
      hooks:
          - id: mypy
            additional_dependencies:
            - types-redis
            - types-requests
