services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  session_manager:
    build:
      context: .
    command: poetry run gunicorn -w 4 -b 0.0.0.0:5000 oversee.session_manager:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build:
      context: .
    command: poetry run celery -A oversee.worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - session_manager

  runner:
    build:
      context: .
    command: poetry run python -m oversee.runner
    depends_on:
      - worker
    volumes:
      - .:/app
