# General constants
SESSION_CREATION_DELAY = 1.5
SESSION_KEEP_ALIVE_DELAY = 60
WORKER_JOB_DURATION = 3
WORKER_CREATION_DELAY = 1
NUMBER_OF_WORKERS = 10

# Redis constants
REDIS_URL = "redis://redis:6379/0"

# Session manager URL
SESSION_MANAGER_URL = "http://session_manager:5000"
SESSION_MANAGER_TIMEOUT = 60
